services:
  coffee-order:
    image: postgres:alpine
    container_name: coffee-order
    ports:
      - "6003:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spring-2024